---
build_from:
  amd64: ghcr.io/hassio-addons/base:12.2.3
  armv7: ghcr.io/hassio-addons/base:12.2.3
  aarch64: ghcr.io/hassio-addons/base:12.2.3
  armhf: ghcr.io/hassio-addons/base:12.2.3
  i386: ghcr.io/hassio-addons/base:12.2.3
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@degatano.com
