---
name: CI

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 4 * * *"
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  workflows:
    uses: mdegat01/addon-workflows/.github/workflows/addon-ci.yaml@main
