---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  workflows:
    uses: mdegat01/addon-workflows/.github/workflows/release-drafter.yaml@main
